# Generated by Django 5.0 on 2025-10-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='voted_at',
        ),
    ]
